Feature/itrex 355
IT-REX-Platform/Frontend pull request #44
Opened 2021-01-31 14:19 UTC by anna-riesch

Frontend Component for Upload Video

2021-01-31 19:30 UTC, Well5a requested changes
Sieht gut aus! Bin jetzt erstmal nur grob über den Code gegangen, würde mir das morgen noch richtig anschauen. Das handling der File können wir dann auch in dem Connection ticket machen, falls ich es richtig verstehe und hier noch nicht passiert.

2021-01-31 19:30 UTC, Well5a commented on src/components/UploadVideoComponent.tsx
> +/*TODO: Configure Video-Upload for iOS as specified here: https://docs.expo.io/versions/latest/sdk/document-picker/*/
Was ist mit diesem Todo?

2021-01-31 19:30 UTC, Well5a commented on src/components/UploadVideoComponent.tsx
> +        console.log(result.uri);
console logs entfernen, sind nur für Testzwecke oder?

2021-01-31 19:30 UTC, Well5a commented on src/components/UploadVideoComponent.tsx
> +        /*TODO: evtl. await  */
Was ist mit diesem Todo?

2021-01-31 19:30 UTC, Well5a commented on src/components/UploadVideoComponent.tsx
> +        console.log("Video Name: ", videoName);
sehe ich das richtig, dass wir hier nur den videonamen übergeben und nicht das File selber? Wie wird das file verarbeitet?

2021-02-01 18:09 UTC, Well5a commented on src/components/UploadVideoComponent.tsx
> +/*TODO: Configure Video-Upload for iOS as specified here: https://docs.expo.io/versions/latest/sdk/document-picker/*/
Muss auf mac gefixed werden -> später

2021-02-02 09:31 UTC, GarondEisenfaust approved these changes

2021-02-02 09:32 UTC, GarondEisenfaust commented
Warum können wir das nicht mergen?

2021-02-02 09:44 UTC, GarondEisenfaust commented
@Well5a glaub du musst das freigeben

2021-02-02 10:14 UTC, Well5a commented
> Warum können wir das nicht mergen?

Die Tests sind noch schlecht, habe da erstmal nur Stubs eingefügt.

2021-02-02 10:14 UTC, Well5a approved these changes

2021-02-02 10:15 UTC, Well5a requested changes
Write/Complete tests for UploadVideoComponent

2021-02-16 18:02 UTC, Well5a approved these changes

2021-02-16 18:03 UTC, Noeliel submitted a review, later dismissed

2021-02-16 18:06 UTC, Well5a approved these changes

2021-02-16 22:28 UTC, merged